name: "treefmt"
on:
  pull_request:
    branches:
      - main
jobs:
  treefmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@V28
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Run treefmt
        run: nix develop --command treefmt --fail-on-change
